### ISSUE TITLE
mail-compose component breaks due to attachments

### ISSUE THREAD

**Issue by Neel-shetty** [nizzyabi/Mail0#20]
Choose a file with a long name, the input fields and the attachment component goes out of bounds.

![Image](https://github.com/user-attachments/assets/978c434e-24b3-484c-b539-9c8645122d77)

selecting multiple attachments makes it take up the whole screen and pushes others out of screen.

![Image](https://github.com/user-attachments/assets/ed11b55f-22cd-4e95-915f-5a4227361e9b)

**Comment by mnoebauer** [comment]
i will adress this

**Comment by HSp4m** [comment]
Fixed #41

**Comment by master-senses** [comment]
@Neel-shetty could you close this issue?

**Comment by Neel-shetty** [comment]
The 2nd Issue I mentioned still persists, just in a different form. 
Let me know if i am nitpicking tho.

![Image](https://github.com/user-attachments/assets/c7508252-9189-4953-96f5-4f8e0172e84d)

**Comment by HSp4m** [comment]
> The 2nd Issue I mentioned still persists, just in a different form. Let me know if i am nitpicking tho.
> 
> ![Image](https://github.com/user-attachments/assets/c7508252-9189-4953-96f5-4f8e0172e84d)

It works for me. Can you try again?
